import { defineConfig } from 'vite';
import { resolve } from 'path';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import vue from '@vitejs/plugin-vue';
import builtins from 'builtin-modules';
import { copyFileSync } from 'fs';

// 构建横幅信息
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

// 自定义插件：复制 manifest.json 到根目录
const copyManifestPlugin = {
  name: 'copy-manifest',
  closeBundle() {
    const manifestPath = resolve(__dirname, 'manifest.json');
    const destPath = resolve(__dirname, '../../manifest.json');
    
    try {
      copyFileSync(manifestPath, destPath);
      console.log('✓ manifest.json copied to root directory');
    } catch (error) {
      console.error('Failed to copy manifest.json:', error);
    }
  }
};

export default defineConfig(({ mode }) => {
  const isProd = mode === 'production';
  
  return {
    // 添加Vue插件支持
    plugins: [
      vue(), // Vue单文件组件支持
    ],
    
    // 定义构建配置
    build: {
      lib: {
        // 入口文件
        entry: resolve(__dirname, 'src/main.ts'),
        // 指定输出格式为 CommonJS
        formats: ['cjs'],
        // 文件名
        fileName: () => 'main.js',
      },
      // 输出目录（默认为当前目录）
      outDir: '../..',
      // 清空输出目录（关闭，因为我们希望保留其他文件）
      emptyOutDir: false,
      // 生产环境下不生成 sourcemap
      sourcemap: isProd ? false : 'inline' as const,
      // 压缩选项
      minify: isProd,
      // 启用 tree-shaking
      treeshaking: true,
      // 指定 rollup 选项
      rollupOptions: {
        // 外部依赖，不打包进结果文件
        external: [
          'obsidian',
          'electron',
          '@codemirror/autocomplete',
          '@codemirror/collab',
          '@codemirror/commands',
          '@codemirror/language',
          '@codemirror/lint',
          '@codemirror/search',
          '@codemirror/state',
          '@codemirror/view',
          '@lezer/common',
          '@lezer/highlight',
          '@lezer/lr',
          ...builtins,
        ],
        // 输出选项
        output: {
          // 添加横幅信息
          banner,
          // 指定输出格式
          format: 'cjs',
          // 指定扩展名
          entryFileNames: 'main.js',
          // 自定义资源文件名（包括CSS）
          assetFileNames: (assetInfo: any) => {
            // 如果是CSS文件，使用自定义名称
            if (assetInfo.name && assetInfo.name.endsWith('.css')) {
              return 'styles.css'; // 自定义CSS文件名
            }
            // 其他资源保持默认命名
            return '[name].[ext]';
          },
        },
        // 添加插件
        plugins: [
          copyManifestPlugin,
          nodeResolve({
            browser: true,
          }),
        ],
      },
    },
  };
}); 