import { App, FuzzySuggestModal, FuzzyMatch, Modal, setIcon } from "obsidian";

/**
 * 图标数组 - 从原项目复制的完整图标列表
 */
const appIcons: string[] = [
  // from obsidian app.js file
  "Custom",
  "editingToolbar",
  "editingToolbarSub",
  "editingToolbarAdd",
  "editingToolbarDelete",
  "editingToolbarReload",
  "codeblock-glyph",
  "underline-glyph",
  "superscript-glyph",
  "subscript-glyph",
  "bot-glyph",
  "header-1",
  "header-2",
  "header-3",
  "header-4",
  "header-5",
  "header-6",
  "header-n",
  "obsidian",
  "obsidian-new",
  "accessibility",
  "activity",
  "air-vent",
  "airplay",
  "alarm-check",
  "alarm-clock-off",
  "alarm-clock",
  "alarm-minus",
  "alarm-plus",
  "album",
  "alert-circle",
  "alert-octagon",
  "alert-triangle",
  "align-center-horizontal",
  "align-center-vertical",
  "align-center",
  "align-end-horizontal",
  "align-end-vertical",
  "align-horizontal-distribute-center",
  "align-horizontal-distribute-end",
  "align-horizontal-distribute-start",
  "align-horizontal-justify-center",
  "align-horizontal-justify-end",
  "align-horizontal-justify-start",
  "align-horizontal-space-around",
  "align-horizontal-space-between",
  "align-justify",
  "align-left",
  "align-right",
  "align-start-horizontal",
  "align-start-vertical",
  "align-vertical-distribute-center",
  "align-vertical-distribute-end",
  "align-vertical-distribute-start",
  "align-vertical-justify-center",
  "align-vertical-justify-end",
  "align-vertical-justify-start",
  "align-vertical-space-around",
  "align-vertical-space-between",
  "anchor",
  "angry",
  "annoyed",
  "aperture",
  "apple",
  "archive-restore",
  "archive",
  "armchair",
  "arrow-big-down",
  "arrow-big-left",
  "arrow-big-right",
  "arrow-big-up",
  "arrow-down-circle",
  "arrow-down-left",
  "arrow-down-right",
  "arrow-down",
  "arrow-left-circle",
  "arrow-left-right",
  "arrow-left",
  "arrow-right-circle",
  "arrow-right",
  "arrow-up-circle",
  "arrow-up-left",
  "arrow-up-right",
  "arrow-up",
  "asterisk",
  "at-sign",
  "award",
  "axe",
  "axis-3d",
  "baby",
  "backpack",
  "baggage-claim",
  "banana",
  "banknote",
  "bar-chart-2",
  "bar-chart-3",
  "bar-chart-4",
  "bar-chart-horizontal",
  "bar-chart",
  "baseline",
  "bath",
  "battery-charging",
  "battery-full",
  "battery-low",
  "battery-medium",
  "battery",
  "beaker",
  "bed-double",
  "bed-single",
  "bed",
  "beer",
  "bell-minus",
  "bell-off",
  "bell-plus",
  "bell-ring",
  "bell",
  "bike",
  "binary",
  "bitcoin",
  "bluetooth-connected",
  "bluetooth-off",
  "bluetooth-searching",
  "bluetooth",
  "bold",
  "bomb",
  "bone",
  "book-open",
  "book",
  "bookmark-minus",
  "bookmark-plus",
  "bookmark",
  "bot",
  "box-select",
  "box",
  "boxes",
  "briefcase",
  "brush",
  "bug",
  "building-2",
  "building",
  "bus",
  "cake",
  "calculator",
  "calendar-check-2",
  "calendar-check",
  "calendar-clock",
  "calendar-days",
  "calendar-heart",
  "calendar-minus",
  "calendar-off",
  "calendar-plus",
  "calendar-range",
  "calendar-search",
  "calendar-x2",
  "calendar-x",
  "calendar",
  "camera-off",
  "camera",
  "car",
  "carrot",
  "cast",
  "check-circle-2",
  "check-circle",
  "check-square",
  "check",
  "chef-hat",
  "cherry",
  "chevron-down",
  "chevron-first",
  "chevron-last",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "chevrons-down-up",
  "chevrons-down",
  "chevrons-left-right",
  "chevrons-left",
  "chevrons-right-left",
  "chevrons-right",
  "chevrons-up-down",
  "chevrons-up",
  "chrome",
  "cigarette-off",
  "cigarette",
  "circle-dot",
  "circle-ellipsis",
  "circle-slashed",
  "circle",
  "citrus",
  "clapperboard",
  "clipboard-check",
  "clipboard-copy",
  "clipboard-edit",
  "clipboard-list",
  "clipboard-signature",
  "clipboard-type",
  "clipboard-x",
  "clipboard",
  "clock-1",
  "clock-10",
  "clock-11",
  "clock-12",
  "clock-2",
  "clock-3",
  "clock-4",
  "clock-5",
  "clock-6",
  "clock-7",
  "clock-8",
  "clock-9",
  "clock",
  "cloud-cog",
  "cloud-drizzle",
  "cloud-fog",
  "cloud-hail",
  "cloud-lightning",
  "cloud-moon-rain",
  "cloud-moon",
  "cloud-off",
  "cloud-rain-wind",
  "cloud-rain",
  "cloud-snow",
  "cloud-sun-rain",
  "cloud-sun",
  "cloud",
  "cloudy",
  "clover",
  "code-2",
  "code",
  "codepen",
  "codesandbox",
  "coffee",
  "cog",
  "coins",
  "columns",
  "command",
  "compass",
  "component",
  "contact",
  "contrast",
  "cookie",
  "copy",
  "copyleft",
  "copyright",
  "corner-down-left",
  "corner-down-right",
  "corner-left-down",
  "corner-left-up",
  "corner-right-down",
  "corner-right-up",
  "corner-up-left",
  "corner-up-right",
  "cpu",
  "credit-card",
  "croissant",
  "crop",
  "cross",
  "crosshair",
  "crown",
  "cup-soda",
  "curly-braces",
  "currency",
  "database",
  "delete",
  "diamond",
  "dice-1",
  "dice-2",
  "dice-3",
  "dice-4",
  "dice-5",
  "dice-6",
  "dices",
  "diff",
  "disc",
  "divide-circle",
  "divide-square",
  "divide",
  "dollar-sign",
  "download-cloud",
  "download",
  "dribbble",
  "droplet",
  "droplets",
  "drumstick",
  "edit-2",
  "edit-3",
  "edit",
  "egg-fried",
  "egg",
  "equal-not",
  "equal",
  "eraser",
  "euro",
  "expand",
  "external-link",
  "eye-off",
  "eye",
  "facebook",
  "factory",
  "fast-forward",
  "feather",
  "figma",
  "file-archive",
  "file-audio-2",
  "file-audio",
  "file-axis-3d",
  "file-badge-2",
  "file-badge",
  "file-bar-chart-2",
  "file-bar-chart",
  "file-box",
  "file-check-2",
  "file-check",
  "file-clock",
  "file-code",
  "file-cog-2",
  "file-cog",
  "file-diff",
  "file-digit",
  "file-down",
  "file-edit",
  "file-heart",
  "file-image",
  "file-input",
  "file-json-2",
  "file-json",
  "file-key-2",
  "file-key",
  "file-line-chart",
  "file-lock-2",
  "file-lock",
  "file-minus-2",
  "file-minus",
  "file-output",
  "file-pie-chart",
  "file-plus-2",
  "file-plus",
  "file-question",
  "file-scan",
  "file-search-2",
  "file-search",
  "file-signature",
  "file-spreadsheet",
  "file-symlink",
  "file-terminal",
  "file-text",
  "file-type-2",
  "file-type",
  "file-up",
  "file-video-2",
  "file-video",
  "file-volume-2",
  "file-volume",
  "file-warning",
  "file-x2",
  "file-x",
  "file",
  "files",
  "film",
  "filter",
  "fingerprint",
  "flag-off",
  "flag-triangle-left",
  "flag-triangle-right",
  "flag",
  "flame",
  "flashlight-off",
  "flashlight",
  "flask-conical",
  "flask-round",
  "flip-horizontal-2",
  "flip-horizontal",
  "flip-vertical-2",
  "flip-vertical",
  "flower-2",
  "flower",
  "focus",
  "folder-archive",
  "folder-check",
  "folder-clock",
  "folder-closed",
  "folder-cog-2",
  "folder-cog",
  "folder-down",
  "folder-edit",
  "folder-heart",
  "folder-input",
  "folder-key",
  "folder-lock",
  "folder-minus",
  "folder-open",
  "folder-output",
  "folder-plus",
  "folder-search-2",
  "folder-search",
  "folder-symlink",
  "folder-tree",
  "folder-up",
  "folder-x",
  "folder",
  "folders",
  "form-input",
  "forward",
  "frame",
  "framer",
  "frown",
  "fuel",
  "function-square",
  "gamepad-2",
  "gamepad",
  "gauge",
  "gavel",
  "gem",
  "ghost",
  "gift",
  "git-branch-plus",
  "git-branch",
  "git-commit",
  "git-compare",
  "git-fork",
  "git-merge",
  "git-pull-request-closed",
  "git-pull-request-draft",
  "git-pull-request",
  "github",
  "gitlab",
  "glass-water",
  "glasses",
  "globe-2",
  "globe",
  "grab",
  "graduation-cap",
  "grape",
  "grid",
  "grip-horizontal",
  "grip-vertical",
  "hammer",
  "hand-metal",
  "hand",
  "hard-drive",
  "hard-hat",
  "hash",
  "haze",
  "headphones",
  "heart-crack",
  "heart-handshake",
  "heart-off",
  "heart-pulse",
  "heart",
  "help-circle",
  "hexagon",
  "highlighter",
  "history",
  "home",
  "hourglass",
  "ice-cream",
  "image-minus",
  "image-off",
  "image-plus",
  "image",
  "import",
  "inbox",
  "indent",
  "indian-rupee",
  "infinity",
  "info",
  "inspect",
  "instagram",
  "italic",
  "japanese-yen",
  "joystick",
  "key",
  "keyboard",
  "lamp-ceiling",
  "lamp-desk",
  "lamp-floor",
  "lamp-wall-down",
  "lamp-wall-up",
  "lamp",
  "landmark",
  "languages",
  "laptop-2",
  "laptop",
  "lasso-select",
  "lasso",
  "laugh",
  "layers",
  "layout-dashboard",
  "layout-grid",
  "layout-list",
  "layout-template",
  "layout",
  "leaf",
  "library",
  "life-buoy",
  "lightbulb-off",
  "lightbulb",
  "line-chart",
  "link-2off",
  "link-2",
  "link",
  "linkedin",
  "list-checks",
  "list-end",
  "list-minus",
  "list-music",
  "list-ordered",
  "list-plus",
  "list-start",
  "list-video",
  "list-x",
  "list",
  "loader-2",
  "loader",
  "locate-fixed",
  "locate-off",
  "locate",
  "lock",
  "log-in",
  "log-out",
  "luggage",
  "magnet",
  "mail-check",
  "mail-minus",
  "mail-open",
  "mail-plus",
  "mail-question",
  "mail-search",
  "mail-warning",
  "mail-x",
  "mail",
  "mails",
  "map-pin-off",
  "map-pin",
  "map",
  "martini",
  "maximize-2",
  "maximize",
  "medal",
  "megaphone-off",
  "megaphone",
  "meh",
  "menu",
  "message-circle",
  "message-square",
  "mic-2",
  "mic-off",
  "mic",
  "microscope",
  "milestone",
  "minimize-2",
  "minimize",
  "minus-circle",
  "minus-square",
  "minus",
  "monitor-off",
  "monitor-speaker",
  "monitor",
  "moon",
  "more-horizontal",
  "more-vertical",
  "mountain-snow",
  "mountain",
  "mouse-pointer-2",
  "mouse-pointer-click",
  "mouse-pointer",
  "mouse",
  "move-3d",
  "move-diagonal-2",
  "move-diagonal",
  "move-horizontal",
  "move-vertical",
  "move",
  "music-2",
  "music-3",
  "music-4",
  "music",
  "navigation-2off",
  "navigation-2",
  "navigation-off",
  "navigation",
  "network",
  "newspaper",
  "octagon",
  "option",
  "outdent",
  "package-2",
  "package-check",
  "package-minus",
  "package-open",
  "package-plus",
  "package-search",
  "package-x",
  "package",
  "paint-bucket",
  "paintbrush-2",
  "paintbrush",
  "palette",
  "palmtree",
  "paperclip",
  "party-popper",
  "pause-circle",
  "pause-octagon",
  "pause",
  "pen-tool",
  "pencil",
  "percent",
  "person-standing",
  "phone-call",
  "phone-forwarded",
  "phone-incoming",
  "phone-missed",
  "phone-off",
  "phone-outgoing",
  "phone",
  "pie-chart",
  "piggy-bank",
  "pin-off",
  "pin",
  "pipette",
  "pizza",
  "plane",
  "play-circle",
  "play",
  "plug-zap",
  "plus-circle",
  "plus-square",
  "plus",
  "pocket",
  "podcast",
  "pointer",
  "pound-sterling",
  "power-off",
  "power",
  "printer",
  "puzzle",
  "qr-code",
  "quote",
  "radio-receiver",
  "radio",
  "recycle",
  "redo-2",
  "redo",
  "refresh-ccw",
  "refresh-cw",
  "regex",
  "repeat-1",
  "repeat",
  "reply-all",
  "reply",
  "rewind",
  "rocket",
  "rocking-chair",
  "rotate-3d",
  "rotate-ccw",
  "rotate-cw",
  "rss",
  "ruler",
  "russian-ruble",
  "save",
  "scale-3d",
  "scale",
  "scaling",
  "scan-face",
  "scan-line",
  "scan",
  "scissors",
  "screen-share-off",
  "screen-share",
  "scroll",
  "search",
  "send",
  "separator-horizontal",
  "separator-vertical",
  "server-cog",
  "server-crash",
  "server-off",
  "server",
  "settings-2",
  "settings",
  "share-2",
  "share",
  "sheet",
  "shield-alert",
  "shield-check",
  "shield-close",
  "shield-off",
  "shield",
  "shirt",
  "shopping-bag",
  "shopping-cart",
  "shovel",
  "shrink",
  "shrub",
  "shuffle",
  "sidebar-close",
  "sidebar-open",
  "sidebar",
  "sigma",
  "signal-high",
  "signal-low",
  "signal-medium",
  "signal-zero",
  "signal",
  "siren",
  "skip-back",
  "skip-forward",
  "skull",
  "slack",
  "slash",
  "slice",
  "sliders-horizontal",
  "sliders",
  "smartphone-charging",
  "smartphone",
  "smile-plus",
  "smile",
  "snowflake",
  "sofa",
  "sort-asc",
  "sort-desc",
  "speaker",
  "sprout",
  "square",
  "star-half",
  "star-off",
  "star",
  "stethoscope",
  "sticker",
  "sticky-note",
  "stop-circle",
  "stretch-horizontal",
  "stretch-vertical",
  "strikethrough",
  "subscript",
  "sun-dim",
  "sun-medium",
  "sun-moon",
  "sun-snow",
  "sun",
  "sunrise",
  "sunset",
  "superscript",
  "swiss-franc",
  "switch-camera",
  "sword",
  "swords",
  "syringe",
  "table-2",
  "table",
  "tablet",
  "tag",
  "tags",
  "target",
  "tent",
  "terminal-square",
  "terminal",
  "text-cursor-input",
  "text-cursor",
  "thermometer-snowflake",
  "thermometer-sun",
  "thermometer",
  "thumbs-down",
  "thumbs-up",
  "ticket",
  "timer-off",
  "timer-reset",
  "timer",
  "toggle-left",
  "toggle-right",
  "tornado",
  "toy-brick",
  "train",
  "trash-2",
  "trash",
  "tree-deciduous",
  "tree-pine",
  "trees",
  "trello",
  "trending-down",
  "trending-up",
  "triangle",
  "trophy",
  "truck",
  "tv-2",
  "tv",
  "twitch",
  "twitter",
  "type",
  "umbrella",
  "underline",
  "undo-2",
  "undo",
  "unlink-2",
  "unlink",
  "unlock",
  "upload-cloud",
  "upload",
  "usb",
  "user-check",
  "user-cog",
  "user-minus",
  "user-plus",
  "user-x",
  "user",
  "users",
  "utensils-crossed",
  "utensils",
  "venetian-mask",
  "verified",
  "vibrate-off",
  "vibrate",
  "video-off",
  "video",
  "view",
  "voicemail",
  "volume-1",
  "volume-2",
  "volume-x",
  "volume",
  "wallet",
  "wand-2",
  "wand",
  "watch",
  "waves",
  "webcam",
  "webhook",
  "wifi-off",
  "wifi",
  "wind",
  "wine",
  "wrap-text",
  "wrench",
  "x-circle",
  "x-octagon",
  "x-square",
  "x",
  "youtube",
  "zap-off",
  "zap",
  "zoom-in",
  "zoom-out",
  "create-new",
  "trash",
  "search",
  "right-triangle",
  "document",
  "folder",
  "pencil",
  "left-arrow",
  "right-arrow",
  "three-horizontal-bars",
  "dot-network",
  "audio-file",
  "image-file",
  "pdf-file",
  "gear",
  "documents",
  "blocks",
  "go-to-file",
  "presentation",
  "cross-in-box",
  "microphone",
  "microphone-filled",
  "two-columns",
  "link",
  "popup-open",
  "checkmark",
  "hashtag",
  "left-arrow-with-tail",
  "right-arrow-with-tail",
  "up-arrow-with-tail",
  "down-arrow-with-tail",
  "lines-of-text",
  "vertical-three-dots",
  "pin",
  "magnifying-glass",
  "info",
  "horizontal-split",
  "vertical-split",
  "calendar-with-checkmark",
  "folder-minus",
  "sheets-in-box",
  "up-and-down-arrows",
  "broken-link",
  "cross",
  "any-key",
  "reset",
  "star",
  "crossed-star",
  "dice",
  "filled-pin",
  "enter",
  "help",
  "vault",
  "open-vault",
  "paper-plane",
  "bullet-list",
  "uppercase-lowercase-a",
  "star-list",
  "expand-vertically",
  "languages",
  "switch",
  "pane-layout",
  "install",
  "sync",
  "check-in-circle",
  "sync-small",
  "check-small",
  "paused",
  "forward-arrow",
  "stacked-levels",
  "bracket-glyph",
  "note-glyph",
  "tag-glyph",
  "price-tag-glyph",
  "heading-glyph",
  "bold-glyph",
  "italic-glyph",
  "strikethrough-glyph",
  "highlight-glyph",
  "code-glyph",
  "quote-glyph",
  "link-glyph",
  "bullet-list-glyph",
  "number-list-glyph",
  "checkbox-glyph",
  "undo-glyph",
  "redo-glyph",
  "up-chevron-glyph",
  "down-chevron-glyph",
  "left-chevron-glyph",
  "right-chevron-glyph",
  "percent-sign-glyph",
  "keyboard-glyph",
  "double-up-arrow-glyph",
  "double-down-arrow-glyph",
  "image-glyph",
  "wrench-screwdriver-glyph",
  "clock",
  "plus-with-circle",
  "minus-with-circle",
  "indent-glyph",
  "unindent-glyph",
  "fullscreen",
  "exit-fullscreen",
  "cloud",
  "run-command",
  "compress-glyph",
  "enlarge-glyph",
  "scissors-glyph",
  "up-curly-arrow-glyph",
  "down-curly-arrow-glyph",
  "plus-minus-glyph",
  "links-going-out",
  "links-coming-in",
  "add-note-glyph",
  "duplicate-glyph",
  "clock-glyph",
  "calendar-glyph",
  "command-glyph",
  "dice-glyph",
  "file-explorer-glyph",
  "graph-glyph",
  "import-glyph",
  "navigate-glyph",
  "open-elsewhere-glyph",
  "presentation-glyph",
  "paper-plane-glyph",
  "question-mark-glyph",
  "restore-file-glyph",
  "search-glyph",
  "star-glyph",
  "play-audio-glyph",
  "stop-audio-glyph",
  "tomorrow-glyph",
  "wand-glyph",
  "workspace-glyph",
  "yesterday-glyph",
  "box-glyph",
  "merge-files-glyph",
  "merge-files",
  "two-blank-pages",
  "scissors",
  "paste",
  "paste-text",
  "split",
  "select-all-text",
  "wand",
  "github-glyph",
  "reading-glasses",
  "user-manual-filled",
  "discord-filled",
  "chat-bubbles-filled",
  "experiment-filled",
  "bracket-glyph",
  "box-glyph",
  "check-small",
  "dice-glyph",
  "dice",
  "discord",
  "right-triangle",
  "heading-glyph",
  "help",
  "keyboard-toggle",
  "broken-link",
  "experiment",
  "left-arrow",
  "link",
  "link-glyph",
  "links-coming-in",
  "links-going-out",
  "open-vault",
  "paused",
  "question-mark-glyph",
  "right-arrow",
  "sidebar-left",
  "sidebar-right",
  "sheets-in-box",
  "star-list",
  "sync-small",
  "tabs",
  "uppercase-lowercase-a",
  "vault",
  "stack-horizontal",
  "stack-vertical",
  "stretch-horizontal",
  "stretch-vertical",
  "distribute-space-horizontal",
  "distribute-space-vertical"
];

/**
 * 图标选择器返回结果类型
 */
export interface IconSelectResult {
  iconName: string;
}

/**
 * 自定义SVG图标输入模态框
 */
class CustomIconModal extends Modal {
  private resolveCallback: ((value: string | null) => void) | null = null;
  private currentValue: string = "";

  constructor(app: App, initialValue?: string) {
    super(app);
    this.currentValue = initialValue || "";
    this.containerEl.addClass("editingToolbar-Modal");
    this.containerEl.addClass("customicon");
  }

  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("b", { text: "输入图标代码，格式为 <svg>.... </svg>" });
    
    const textComponent = document.createElement("textarea");
    textComponent.className = "wideInputPromptInputEl";
    textComponent.placeholder = "";
    textComponent.value = this.currentValue;
    textComponent.style.width = "100%";
    textComponent.style.height = "200px";
    contentEl.appendChild(textComponent);
    
    textComponent.addEventListener("input", () => {
      this.currentValue = textComponent.value;
    });

    // 添加确认和取消按钮
    const buttonContainer = contentEl.createDiv({ cls: "custom-icon-buttons" });
    buttonContainer.style.marginTop = "10px";
    buttonContainer.style.display = "flex";
    buttonContainer.style.gap = "10px";
    buttonContainer.style.justifyContent = "flex-end";

    const confirmButton = buttonContainer.createEl("button", { text: "确认" });
    confirmButton.style.padding = "5px 15px";
    confirmButton.addEventListener("click", () => {
      if (this.resolveCallback) {
        this.resolveCallback(this.currentValue);
      }
      this.close();
    });

    const cancelButton = buttonContainer.createEl("button", { text: "取消" });
    cancelButton.style.padding = "5px 15px";
    cancelButton.addEventListener("click", () => {
      if (this.resolveCallback) {
        this.resolveCallback(null);
      }
      this.close();
    });

    // 聚焦到文本框
    textComponent.focus();
  }

  onClose() {
    super.onClose();
    if (this.resolveCallback) {
      this.resolveCallback(null);
    }
  }

  setResolveCallback(callback: (value: string | null) => void) {
    this.resolveCallback = callback;
  }
}

/**
 * 图标选择器模态框
 * 继承 FuzzySuggestModal<string>，提供模糊搜索功能
 */
class IconPickerModal extends FuzzySuggestModal<string> {
  private resolveCallback: ((value: string | null) => void) | null = null;

  constructor(app: App) {
    super(app);
    this.setPlaceholder("选择一个图标");
  }

  /**
   * 复制原项目的文本格式化方法
   */
  private capitalJoin(string: string): string {
    const icon = string.split(" ");
    return icon
      .map((icon) => {
        return icon[0].toUpperCase() + icon.substring(1);
      })
      .join(" ");
  }

  /**
   * 获取所有可用图标
   */
  getItems(): string[] {
    return appIcons;
  }

  /**
   * 获取图标显示文本 - 复制原项目的格式化逻辑
   */
  getItemText(item: string): string {
    return this.capitalJoin(
      item
        .replace("feather-", "")
        .replace("remix-", "")
        .replace("bx-", "")
        .replace(/([A-Z])/g, " $1")
        .trim()
        .replace(/-/gi, " ")
    );
  }

  /**
   * 渲染建议项 - 复制原项目的图标预览功能
   */
  renderSuggestion(icon: FuzzyMatch<string>, iconItem: HTMLElement): void {
    const span = iconItem.createSpan({ cls: "editingToolbarIconPick" });
    setIcon(span, icon.item); // 使用 Obsidian 的 setIcon 渲染图标
    super.renderSuggestion(icon, iconItem);
  }

  /**
   * 当用户选择图标时触发
   */
  async onChooseItem(item: string): Promise<void> {
    // 如果选择了 "Custom"，打开自定义SVG输入框
    if (item === "Custom") {
      const customIcon = await this.openCustomIconInput();
      if (this.resolveCallback) {
        this.resolveCallback(customIcon);
      }
    } else {
      // 选择了内置图标
      if (this.resolveCallback) {
        this.resolveCallback(item);
      }
    }
    this.close();
  }

  /**
   * 打开自定义图标输入框
   */
  private openCustomIconInput(): Promise<string | null> {
    return new Promise((resolve) => {
      const customModal = new CustomIconModal(this.app);
      customModal.setResolveCallback(resolve);
      customModal.open();
    });
  }

  /**
   * 设置Promise的resolve回调
   */
  setResolveCallback(callback: (value: string | null) => void) {
    this.resolveCallback = callback;
  }

  /**
   * 模态框关闭时，如果没有选择则返回null
   */
  onClose() {
    super.onClose();
    if (this.resolveCallback) {
      this.resolveCallback(null);
    }
  }
}

/**
 * 打开图标选择器
 * @param app Obsidian App 实例
 * @returns Promise<string | null> 返回选择的图标名称，取消则返回null
 * 
 * @example
 * // 在Vue组件中使用
 * import { inject } from 'vue';
 * import { openIconSelector } from './iconSelector';
 * 
 * const app = inject('obsidian-app'); // 通过inject获取app对象
 * 
 * const handleSelectIcon = async () => {
 *   const iconName = await openIconSelector(app);
 *   if (iconName) {
 *     console.log('选择的图标:', iconName);
 *   }
 * };
 */
export function openIconSelector(app: App): Promise<string | null> {
  return new Promise((resolve) => {
    const modal = new IconPickerModal(app);
    modal.setResolveCallback(resolve);
    modal.open();
  });
}

/**
 * Vue Composition API 钩子函数
 * 提供更便捷的在Vue组件中使用的方式
 * 
 * @example
 * // 在Vue组件中使用
 * import { useIconSelector } from './iconSelector';
 * 
 * const { selectIcon } = useIconSelector();
 * 
 * const handleClick = async () => {
 *   const iconName = await selectIcon();
 *   if (iconName) {
 *     console.log('选择的图标:', iconName);
 *   }
 * };
 */
export function useIconSelector() {
  // 在Vue组件中，app对象通常通过inject获取
  const selectIcon = async (): Promise<string | null> => {
    // 这里需要在Vue组件内部调用，通过inject获取app
    // 示例中假设app已经通过某种方式获取到了
    throw new Error('请在Vue组件内部使用，并传入通过inject获取的app对象');
  };

  return {
    selectIcon
  };
}
