import { defineConfig } from 'vite';
import { resolve } from 'path';
import * as builtins from 'builtin-modules';
import { copyFileSync } from 'fs';

// 输出文件顶部的横幅信息
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

// 自定义插件：复制 manifest.json 到根目录
const copyManifestPlugin = {
  name: 'copy-manifest',
  closeBundle() {
    const manifestPath = resolve(__dirname, 'manifest.json');
    const destPath = resolve(__dirname, '../../manifest.json');
    
    try {
      copyFileSync(manifestPath, destPath);
      console.log('✓ manifest.json copied to root directory');
    } catch (error) {
      console.error('Failed to copy manifest.json:', error);
    }
  }
};

export default defineConfig({
  build: {
    lib: {
      entry: resolve(__dirname, 'src/main.ts'),
      name: 'ObsidianPlugin',
      fileName: 'main',
      formats: ['cjs']
    },
    rollupOptions: {
      external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins
      ],
      output: {
        banner,
        globals: {
          obsidian: 'obsidian'
        },
        sourcemapExcludeSources: true
      }
    },
    sourcemap: process.env.NODE_ENV !== 'production',
    outDir: '../..',
    emptyOutDir: false,
    minify: process.env.NODE_ENV === 'production',
    target: 'es2018',
    commonjsOptions: {
      transformMixedEsModules: true,
    }
  },
  resolve: {
    alias: {
      'test-module': resolve(__dirname, '../../packages/test-module/src/index.ts')
    }
  },
  plugins: [copyManifestPlugin]
}); 